[package]
name = "ramrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-info = "0.9.1"
sysinfo = "0.28.4"
terminal-menu = "2.0.5"
termion = "2.0.1"
