[package]
name = "ramrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
sys = "0.0.0"
sys-info = "0.9.1"
termion = "2.0.1"
